version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - misspell
    - ineffassign

linters-settings:
  gofmt:
    simplify: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: '.*_test\.go$'
      linters:
        - unparam
        - unused
    - path: '^test/.*'
      linters:
        - unused
        - unparam
    - path: '^test/scenarios/.*\.go$'
      linters:
        - unused

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
